name: Run Continuous Benchmarks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Setup rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: 1.87
          cache-target: release

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run CI Setup
        run: just configure-toolchain-ci

      - name: Build the benchmark target(s)
        # Limiting the number of jobs is an attempt to not violate GitHub's runner resources.
        run: cargo codspeed build --profile codspeed -j4

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: cargo codspeed run