name: Change tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run CI Setup
        run: just ci-setup

      - name: Run CI Recipe
        run: just ci

