name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: 1.90
          cache-target: release

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Run CI Setup
        run: just configure-toolchain-ci

      - name: Run CI Recipe
        run: just prepare-benches-tests test rustdoc

  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Setup rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: 1.90
          cache-target: release

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Run CI Setup
        run: just configure-toolchain-ci

      - name: Run Lints
        run: just lint